In [1]:
## data preprocessing 1

# specific format
# numeric data
# scaling the data

# data preprocessing
# imputing missing value
# handling categorical data
# scaling of data
# normalizarion 
# feature selection



In [2]:
# 1. imputing missing values
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = {'one' : pd.Series([1,2,5],index=['a','b','e']),'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}

table = pd.DataFrame(data)

print(table)

# by default always convert to df any data


   one  two
a  1.0  1.0
b  2.0  2.0
c  NaN  3.0
d  NaN  4.0
e  5.0  NaN


In [11]:
table.isnull()

,one,two
a,False,False
b,False,False
c,True,False
d,True,False
e,False,True


In [ ]:
table.isnull().any()
#  gives column name who have null values


In [19]:
null_val = table.isnull().sum()
type(null_val)

pandas.Series

In [31]:
missing_pct = (null_val/len(table))*100
missing_pct

# how much of a col is not null

one    40.0
two    20.0
dtype: float64

In [8]:
# null handling
# using simple imputer

from sklearn.impute import SimpleImputer

si1 = SimpleImputer(missing_values = np.nan , strategy = 'mean')  # where ever nan replace with mean of that col
# this also for alias

# SHIFT + TAB FOR OFFLINE SUGGESTIONS

si2 = SimpleImputer(missing_values = np.nan , strategy = 'median')

si3 = SimpleImputer(missing_values = np.nan , strategy = 'most_frequent') # for mode 

si3.fit(table) 
temp = si3.transform(table)

# or

# si.fit_transform(table)


# now convert to dataframe
df1 = pd.DataFrame(temp,columns = ['one','two'])

df1

,one,two
0,1.0,1.0
1,2.0,2.0
2,1.0,3.0
3,1.0,4.0
4,5.0,1.0


In [12]:
# using fillna no needed sklearn here

x = table.fillna(20)
x

,one,two
a,1.0,1.0
b,2.0,2.0
c,20.0,3.0
d,20.0,4.0
e,5.0,20.0


# 2.HANDLING CATEGORICAL DATA

## 2.1 Using get_dummies() (from pandas library)

In [15]:
# categorical has textual data also we need to convert to numeric form

# can be nominal and ordinal 

''' nominal -> onehotencoder
           ->  get_dummies 
           
    oridnal -> labelencoder

    number of categories == number of columns created
'''





,one,two
a,1.0,1.0
b,2.0,2.0
c,NaN,3.0
d,NaN,4.0
e,5.0,NaN


In [19]:
data = {'customer_id' :pd.Series([1,2,3,4,5]),'loan_type' : pd.Series(['Home loan','Personal loan','Education loan','Car loan','Home loan']),'Income' : pd.Series(['15k','20k','30k','40k','50k'])}

print(type(data))

data = pd.DataFrame(data)

data

<class 'dict'>


,customer_id,loan_type,Income
0,1,Home loan,15k
1,2,Personal loan,20k
2,3,Education loan,30k
3,4,Car loan,40k
4,5,Home loan,50k


In [26]:
pd.get_dummies(data['loan_type'])
loan_info = pd.get_dummies(data['loan_type'],dtype=int)

print(loan_info)

print()

income_info = pd.get_dummies(data['Income'],dtype=int)

print(income_info)

   Car loan  Education loan  Home loan  Personal loan
0         0               0          1              0
1         0               0          0              1
2         0               1          0              0
3         1               0          0              0
4         0               0          1              0

   15k  20k  30k  40k  50k
0    1    0    0    0    0
1    0    1    0    0    0
2    0    0    1    0    0
3    0    0    0    1    0
4    0    0    0    0    1


In [39]:
whole_data = pd.get_dummies(data,dtype = int,prefix_sep = ' : ')
whole_data

,customer_id,loan_type : Car loan,loan_type : Education loan,loan_type : Home loan,loan_type : Personal loan,Income : 15k,Income : 20k,Income : 30k,Income : 40k,Income : 50k
0,1,0,0,1,0,1,0,0,0,0
1,2,0,0,0,1,0,1,0,0,0
2,3,0,1,0,0,0,0,1,0,0
3,4,1,0,0,0,0,0,0,1,0
4,5,0,0,1,0,0,0,0,0,1


### 2.2 using OneHotEncoder() (from sklearn library)

In [44]:
from sklearn.preprocessing import OneHotEncoder

data = {'customer_id' :pd.Series([1,2,3,4,5]),'loan_type' : pd.Series(['Home loan','Personal loan','Education loan','Car loan','Home loan']),'Income' : pd.Series(['15k','20k','30k','40k','50k'])}

data = pd.DataFrame(data)

one = OneHotEncoder()

one

,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values within a single feature, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute... versionadded:: 0.20",'auto'
,"drop drop: {'first', 'if_binary'} or an array-like of shape (n_features,), default=NoneSpecifies a methodology to use to drop one of the categories perfeature. This is useful in situations where perfectly collinearfeatures cause problems, such as when feeding the resulting datainto an unregularized linear regression model.However, dropping one category breaks the symmetry of the originalrepresentation and can therefore induce a bias in downstream models,for instance for penalized linear classification or regression models.- None : retain all features (the default).- 'first' : drop the first category in each feature. If only one category is present, the feature will be dropped entirely.- 'if_binary' : drop the first category in each feature with two categories. Features with 1 or more than 2 categories are left intact.- array : ``drop[i]`` is the category in feature ``X[:, i]`` that should be dropped.When `max_categories` or `min_frequency` is configured to groupinfrequent categories, the dropping behavior is handled after thegrouping... versionadded:: 0.21 The parameter `drop` was added in 0.21... versionchanged:: 0.23 The option `drop='if_binary'` was added in 0.23... versionchanged:: 1.1 Support for dropping infrequent categories.",None
,"sparse_output sparse_output: bool, default=TrueWhen ``True``, it returns a SciPy sparse matrix/arrayin ""Compressed Sparse Row"" (CSR) format... versionadded:: 1.2 `sparse` was renamed to `sparse_output`",True
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"handle_unknown handle_unknown: {'error', 'ignore', 'infrequent_if_exist', 'warn'}, default='error'Specifies the way unknown categories are handled during :meth:`transform`.- 'error' : Raise an error if an unknown category is present during transform.- 'ignore' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros. In the inverse transform, an unknown category will be denoted as None.- 'infrequent_if_exist' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will map to the infrequent category if it exists. The infrequent category will be mapped to the last position in the encoding. During inverse transform, an unknown category will be mapped to the category denoted `'infrequent'` if it exists. If the `'infrequent'` category does not exist, then :meth:`transform` and :meth:`inverse_transform` will handle an unknown category as with `handle_unknown='ignore'`. Infrequent categories exist based on `min_frequency` and `max_categories`. Read more in the :ref:`User Guide <encoder_infrequent_categories>`.- 'warn' : When an unknown category is encountered during transform a warning is issued, and the encoding then proceeds as described for `handle_unknown=""infrequent_if_exist""`... versionchanged:: 1.1 `'infrequent_if_exist'` was added to automatically handle unknown categories and infrequent categories... versionadded:: 1.6 The option `""warn""` was added in 1.6.",'error'
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.1 Read more in the :ref:`User Guide <encoder_infrequent

In [48]:
x = one.fit_transform(data)
x1 = one.fit_transform(data).toarray()
print(x)
print()
print(x1)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 15 stored elements and shape (5, 14)>
  Coords	Values
  (0, 0)	1.0
  (0, 7)	1.0
  (0, 9)	1.0
  (1, 1)	1.0
  (1, 8)	1.0
  (1, 10)	1.0
  (2, 2)	1.0
  (2, 6)	1.0
  (2, 11)	1.0
  (3, 3)	1.0
  (3, 5)	1.0
  (3, 12)	1.0
  (4, 4)	1.0
  (4, 7)	1.0
  (4, 13)	1.0

[[1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1.]]


In [53]:
from sklearn.preprocessing import LabelEncoder

data = {'customer_id' :pd.Series([1,2,3,4,5]),'loan_type' : pd.Series(['Home loan','Personal loan','Education loan','Car loan','Home loan']),'Income' : pd.Series(['15k','20k','30k','40k','50k'])}

data = pd.DataFrame(data)

le = LabelEncoder()
le



LabelEncoder()

In [56]:
# x = le.fit_transform(data)
# above gives error

x = data.apply(le.fit_transform)
x

,customer_id,loan_type,Income
0,0,2,0
1,1,3,1
2,2,1,2
3,3,0,3
4,4,2,4


# 3. Scaling of Data

### 3.1 MinMax Scaler
### 3.2 Standard Scaler
### 3.3 Robust Scaler

In [ ]:
'''
SCALING IS TO MAKE TO RANGE OF DATA BETWEEN A CERTAIN RANGE OF WHOLE DATASET

3.1 minmax 
x = (x - xmin) / (xmax - xmin)

3.2 Standard scaler
x = (x - μ) /  σ 

3.3 Robust Scaler
x = (x - median) / IQR

'''

In [64]:
data = np.array([[-100.3],[27.5],[0],[-200],[1000]])



print('before scaling \n',data,'\n')



before scaling 
 [[-100.3]
 [  27.5]
 [   0. ]
 [-200. ]
 [1000. ]] 



In [70]:
from sklearn import preprocessing

mm = preprocessing.MinMaxScaler()
mm1 = preprocessing.MinMaxScaler(feature_range=(5,10))
mm2 = preprocessing.MinMaxScaler(feature_range=(100,200))


In [71]:
scaled = mm2.fit_transform(data)

scaled

array([[108.30833333],
       [118.95833333],
       [116.66666667],
       [100.        ],
       [200.        ]])

In [72]:
ss = preprocessing.StandardScaler()


,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True


In [73]:
x = ss.fit_transform(data)
x
# -3 to 3 range here

array([[-0.56524004],
       [-0.27128026],
       [-0.33453451],
       [-0.79456547],
       [ 1.96562028]])

In [76]:
rs = preprocessing.RobustScaler()

x = rs.fit_transform(data)
x

array([[-0.78482003],
       [ 0.21517997],
       [ 0.        ],
       [-1.56494523],
       [ 7.82472613]])