In [1]:
import pandas as pd 
import numpy as np 
import matplotlib as plt
from functools import reduce


In [2]:
# 38. From a list of words, join them to form a complete sentence.
lst = ["khanjan"," python "," AI ","DA"]

str1 = reduce(lambda x,y:x+y,lst)

print(str1)

khanjan python  AI DA


# NUMPY

In [3]:
# 1. Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100.
# 2. Write a NumPy program to combine a one and a two-dimensional array together and
# display their elements.
# 3. Write a NumPy program to compute the multiplication of two given matrixes.
# 4. Write a NumPy program to compute the cross product of two given matrixes.


In [4]:
a = np.arange(1, 100)

result = np.array(list(filter(lambda x:x%3 == 0 or x%5 == 0,a)))

print("Multiples:", result)
print("Sum:", np.sum(result))

Multiples: [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
Sum: 2318


In [5]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6],
              [7, 8, 9]])

c = np.vstack((a, b))

print(c)
# Here a is 1D and b is 2D. vstack() combines them vertically.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

c = np.dot(a, b)

# For matrix multiplication, use np.dot() or @.

print(c)

[[19 22]
 [43 50]]


In [7]:
# For the usual 3D cross product:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.cross(a, b)

print(c)

[-3  6 -3]


In [8]:
# 5. Write a NumPy program to compute the determinant of a given square array.
# 6. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given
# square array.
# 7. Write a NumPy program to compute the inverse of a given matrix.
# 8. Write a NumPy program to compute the mean, standard deviation, and variance of a given
# array along the second axis.

In [9]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,6,9],
])

print(np.linalg.det(mat))

-12.0


In [10]:
a = np.array([[1, 2],
              [2, 1]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 3.+0.j -1.+0.j]
Eigenvectors:
[[ 0.70710678+0.j -0.70710678+0.j]
 [ 0.70710678+0.j  0.70710678+0.j]]


In [11]:
mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,6,9],
])

print(np.linalg.inv(mat))

[[-7.50000000e-01 -1.26882631e-16  2.50000000e-01]
 [-5.00000000e-01  1.00000000e+00 -5.00000000e-01]
 [ 9.16666667e-01 -6.66666667e-01  2.50000000e-01]]


In [12]:

a = np.array([[1, 2, 3],
              [4, 5, 6]])

mean = np.mean(a, axis=1)
std = np.std(a, axis=1)
var = np.var(a, axis=1)

print("Mean:", mean)
print("Standard Deviation:", std)
print("Variance:", var)

# For a 2D NumPy array:
# axis=0 → column-wise operation
# axis=1 → row-wise operation

Mean: [2. 5.]
Standard Deviation: [0.81649658 0.81649658]
Variance: [0.66666667 0.66666667]


In [13]:
# 9. Write a NumPy program to compute the covariance matrix of two given arrays.
# 10. Create a 1D NumPy array of numbers from 1 to 10.
# 11. Create a 1D NumPy array of 10 zeros.
# 12. Create a 1D NumPy array of 10 ones.
# 13. Create a 1D NumPy array of 10 fives.
# 14. Create a 1D array of numbers from 10 to 50.
# 15. Create a 1D array of even numbers from 10 to 50

In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

cov_matrix = np.cov(a, b)

print(cov_matrix)

[[ 2.5 -2.5]
 [-2.5  2.5]]


In [15]:
lst = np.arange(1,11)

print(lst)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
lst0 = np.full(10,0)
print(lst0)

lst1 = np.full(10,1)
print(lst1)

lst5 = np.full(10,5)
print(lst5)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


In [17]:
# even number 10-50a

evens = np.arange(10,51,2)

print(evens)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [18]:
# 16. Create a 1D array of odd numbers from 1 to 20.
# 17. Create a 3x3 matrix with values ranging from 0 to 8.
# 18. Create a 3x3 identity matrix.
# 19. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.
# 20. Create an array of 100 equally spaced points between 0 and 1.
# 21. Create an array of 25 random numbers sampled from a standard normal distribution.
# 22. Create a 10x10 matrix with values from 0.01 to 1.00.

In [19]:
odds = np.arange(1,21,2)
print(odds)

[ 1  3  5  7  9 11 13 15 17 19]


In [20]:
nums = np.arange(0,9)

mat = nums.reshape(3,3)

print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
mat = np.eye(3) # for 3x3

print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
mat = np.diag([1,2,3,4],k=-1)

print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [23]:
a = np.linspace(0, 1, 100)

print(a)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [24]:
a = np.random.randn(25)

print(a)

# randn() generates random values from the standard normal distribution (mean = 0, standard deviation = 1).

[-0.02388029  0.09114735 -0.45977557  0.52078648 -0.91114618 -1.24561394
  0.40171941  1.00244305 -0.69646872 -1.61185415  0.74007338 -0.99088172
  0.28202132  0.18334425  2.1221032  -1.52255828 -2.22096927 -0.06511888
  1.1068956   0.98688345 -0.37996893 -0.74473296  0.91227786  0.23125659
  0.33541047]


In [25]:
values = np.arange(0.01,1.01,0.01)
print(values.reshape(10,10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [26]:
# 23. Create a 5x5 matrix with row values ranging from 0 to 4.
# 24. Create a 5x5 matrix with column values ranging from 0 to 4.
# 25. Create a 10x10 matrix with 1 on the border and 0 inside.
# 26. Create a 5x5 matrix with random values and find its maximum and minimum values.
# 27. Create a random vector of size 30 and find the mean value.
# 28. Create a 10x10 matrix with random values and normalize it.
# 29. Create a 5x5 matrix with random values and subtract the row mean.
# 30. Create a checkerboard 8x8 matrix using slicing.
# 31. Create a checkerboard 8x8 matrix using tile function.

In [27]:
mat = np.tile(np.arange(0,5),(5,1))

print(mat)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [28]:
t = np.arange(0,5).reshape(5,1)
print(t)

mat = np.tile(t,(1,5))
print(mat)

[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [29]:
mat = np.full(100,1).reshape(10,10)
# print(mat)

mat[1:-1,1:-1] = 0

print(mat) 

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [30]:
mat = np.random.randint(0,21,25).reshape(5,5)

print(mat)

print(np.min(mat))
print(np.max(mat))

[[ 9  1 10  8 13]
 [ 4  5 18 18  0]
 [20  8 19 11 16]
 [11  6  5 15 16]
 [11 11 12 15 12]]
0
20


In [31]:

a = np.random.rand(30)

# print(a)
print(a.shape)

print("Mean:", a.mean())

(30,)
Mean: 0.5104529771418745


In [32]:
a = np.random.randint(0,71,100).reshape(10,10)

normalised = (a - a.min()) / (a.max() - a.min())  # between 0 and 1
print(a)
print(normalised)

[[70 49 65 18 31 66 23 64 63 57]
 [43 41 43 54 48 50 52 69 53 13]
 [25 21 22 32 21 47 54 61 22  3]
 [10  9 70 34  4 30 20 46 54 14]
 [ 1 42 35  6 31 37 15 48 31 66]
 [10 49 58 26 17 42  0 11 59 34]
 [21  0 20 58 49 34 49 51 53  2]
 [48 39 50  5 67 18 10  4 36 25]
 [14 36 13 37 34  4 23 52 50 18]
 [61  2 54 55 66 50 62 27 63  8]]
[[1.         0.7        0.92857143 0.25714286 0.44285714 0.94285714
  0.32857143 0.91428571 0.9        0.81428571]
 [0.61428571 0.58571429 0.61428571 0.77142857 0.68571429 0.71428571
  0.74285714 0.98571429 0.75714286 0.18571429]
 [0.35714286 0.3        0.31428571 0.45714286 0.3        0.67142857
  0.77142857 0.87142857 0.31428571 0.04285714]
 [0.14285714 0.12857143 1.         0.48571429 0.05714286 0.42857143
  0.28571429 0.65714286 0.77142857 0.2       ]
 [0.01428571 0.6        0.5        0.08571429 0.44285714 0.52857143
  0.21428571 0.68571429 0.44285714 0.94285714]
 [0.14285714 0.7        0.82857143 0.37142857 0.24285714 0.6
  0.         0.15714286 0.8428571

In [33]:
a = np.random.rand(5, 5)

row_mean = a.mean(axis=1, keepdims=True)
# axis=1 calculates the mean of each row.
print(row_mean)

print()
result = a - row_mean

print(result)

[[0.29341819]
 [0.54282829]
 [0.56559979]
 [0.65758592]
 [0.4192653 ]]

[[-0.06001169  0.4618388  -0.26902591  0.07784011 -0.21064131]
 [ 0.23263454  0.26339695 -0.2600372  -0.47325319  0.23725891]
 [ 0.29888007 -0.34338238 -0.41035155  0.35251994  0.10233392]
 [ 0.31792422 -0.55811953  0.21219505 -0.18720346  0.21520372]
 [-0.38383638  0.09851943  0.3001431  -0.1592211   0.14439495]]


In [34]:
mat = np.full(64,0).reshape(8,8)

# print(mat)


mat[1::2 , ::2] = 1

mat[::2 , 1::2] = 1
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [35]:
t = np.array([
    [0,1],
    [1,0]
])

checker = np.tile(t,(4,4))

print(checker)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [36]:
# 32. Create a 10x3 matrix and sort each column.
# 33. Create a 10x3 matrix and sort each row.

In [42]:
arr = np.random.randint(1, 11, size=(10, 3))
print(arr,'\n')

print(np.sort(arr,axis=0)) # col wise

print()

print(np.sort(arr,axis=1)) # row wise 

[[ 5  6  7]
 [10  4  6]
 [ 9  1  4]
 [ 3  7  7]
 [10 10  9]
 [ 1 10  2]
 [10  5  8]
 [ 6  6  8]
 [ 3  3  8]
 [ 9  6  1]] 

[[ 1  1  1]
 [ 3  3  2]
 [ 3  4  4]
 [ 5  5  6]
 [ 6  6  7]
 [ 9  6  7]
 [ 9  6  8]
 [10  7  8]
 [10 10  8]
 [10 10  9]]

[[ 5  6  7]
 [ 4  6 10]
 [ 1  4  9]
 [ 3  7  7]
 [ 9 10 10]
 [ 1  2 10]
 [ 5  8 10]
 [ 6  6  8]
 [ 3  3  8]
 [ 1  6  9]]


In [47]:
# 34. Create a 5x5 matrix with random values and swap two rows.
arr = np.random.randint(1, 21, size=(5,5))
print(arr)
print()
temp = arr[2].copy()
arr[2] = arr[0]
arr[0] = temp

# swapped 2 and 0th rows

print(arr)


[[ 4  6  5 15  1]
 [ 9  6 10  7 16]
 [ 7 19 20 19 19]
 [18  8  5 19 13]
 [11 12  7 10 10]]

[[ 7 19 20 19 19]
 [ 9  6 10  7 16]
 [ 4  6  5 15  1]
 [18  8  5 19 13]
 [11 12  7 10 10]]


In [50]:
# 35. Create a 5x5 matrix with random values and swap two columns.

arr = np.random.randint(1, 21, size=(5,5))
print(arr,'\n')

transpo = arr.T

temp = transpo[1].copy()
transpo[1] = transpo[3]
transpo[3] = temp

arr = transpo.T
print(arr)


[[12  1  3  5 17]
 [13  6  3 12  3]
 [11 16 12 18  3]
 [ 9 15  8 20 19]
 [ 4 17  7  4 17]] 

[[12  5  3  1 17]
 [13 12  3  6  3]
 [11 18 12 16  3]
 [ 9 20  8 15 19]
 [ 4  4  7 17 17]]


In [53]:
# 36. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

m1 = np.random.randint(1,11,size=(5,3))
m2 = np.random.randint(1,11,size=(3,2))
print(m1)
print(m2)
print(m1@m2)

[[ 2  8  1]
 [ 9  4  7]
 [ 2  7  9]
 [ 2  3  4]
 [10  5  1]]
[[2 4]
 [1 2]
 [4 6]]
[[16 30]
 [50 86]
 [47 76]
 [23 38]
 [29 56]]


In [55]:
# 40. Create a 5x5 matrix and find the sum of all elements.

arr = np.random.randint(1, 21, size=(5,5))

print(np.sum(arr))

247


In [56]:
# 41. Create a 5x5 matrix and find the mean of all elements.

arr = np.random.randint(1, 21, size=(5,5))

print(np.mean(arr))


12.28


In [ ]:
# 37. Create a 5x5 matrix with random integers and find the unique elements.
# 38. Create a 5x5 matrix and find the sum of diagonal elements.
# 39. Create a 4x4 matrix with values 0 to 15 and find the sum by rows and by columns.

In [59]:
a = np.random.randint(1, 21, (5, 5))

print("Matrix:")
print(a)

print("Unique elements:")
print(np.unique(a))

# non duplicates

Matrix:
[[ 3 19 19  8  9]
 [ 5 20 18  6 19]
 [ 6 16  3 19 15]
 [14 15 11  8  6]
 [ 3 12 16 13 14]]
Unique elements:
[ 3  5  6  8  9 11 12 13 14 15 16 18 19 20]


In [60]:
a = np.random.randint(1, 11, (5, 5))

print("Matrix:")
print(a)

print("Sum of diagonal elements:", np.trace(a))

# or print(np.diag(a).sum())

Matrix:
[[ 8  8  2 10 10]
 [ 8  1  5  6  6]
 [ 4  7  5  6  1]
 [ 6  5  3  4  8]
 [ 7  5  1  8  7]]
Sum of diagonal elements: 25


In [61]:
a = np.arange(16).reshape(4, 4)

print("Matrix:")
print(a)

print("Sum by rows:")
print(np.sum(a, axis=1))

print("Sum by columns:")
print(np.sum(a, axis=0))

Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Sum by rows:
[ 6 22 38 54]
Sum by columns:
[24 28 32 36]
